<?php

namespace AppBundle\Repository;

/**
 * LineUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineUpRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllWithPlayers()
    {
        $qb = $this->createQueryBuilder('l');
        $qb
            ->select('l', 'j', 'r')
            ->leftJoin('l.joueurs', 'j')
            ->leftJoin('l.rankMin', 'r')
            ->orderBy('l.rankMin', 'DESC')
            ->addOrderBy('l.nom', 'ASC')
        ;

        return $qb->getQuery()->getResult();
    }
}
