<?php

namespace AppBundle\Repository;

/**
 * LineUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineUpRepository extends \Doctrine\ORM\EntityRepository
{
}
