<?php

namespace AppBundle\Repository;

/**
 * TournoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoisRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearch($mois, $lineUp, $site, $categorie, $resultats)
    {
        $qb = $this->createQueryBuilder('t');
        $qb
            ->select('t', 'l', 's')
            ->leftJoin('t.lineUps', 'l')
            ->leftJoin('t.sites', 's')
            ->orderBy('t.dateTournois', 'DESC')
        ;

        if ($mois != false) {
            $date = new \DateTime('2017-' . $mois . '-01');
            $dateStart = $date->format('Y-m-d');
            $dateEnd = $date->format('Y-m-t');

            $qb
                ->andWhere('t.dateTournois >= :dateStart')
                ->andWhere('t.dateTournois <= :dateEnd')
                ->setParameter(':dateStart', $dateStart)
                ->setParameter(':dateEnd', $dateEnd)
            ;
        }

        if ($lineUp != false) {
            $qb
                ->andWhere('l.id = :lineUp')
                ->setParameter(':lineUp', $lineUp)
            ;
        }

        if ($site != false) {
            $qb
                ->andWhere('s.id = :site')
                ->setParameter(':site', $site)
            ;
        }

        if ($categorie != false) {
            $qb
                ->andWhere('t.types = :categorie')
                ->setParameter(':categorie', $categorie)
            ;
        }

        if ($resultats != false) {
            $qb
                ->andWhere('t.tours >= :resultats')
                ->setParameter(':resultats', $resultats)
            ;
        }


        return $qb->getQuery()->getResult();

    }
}
