app:
    resource: "@AppBundle/Resources/config/routing.yml"

login:
    path:     /login
    defaults: { _controller: "AppBundle:Security:login" }

logout:
    path: /logout

login_check:
    path: /login_check