joueur_index:
    path:     /
    defaults: { _controller: "AppBundle:Joueur:index" }
    methods:  [GET, POST]

joueur_new:
    path:     /new
    defaults: { _controller: "AppBundle:Joueur:new" }
    methods:  [GET, POST]

joueur_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Joueur:edit" }
    methods:  [GET, POST]

joueur_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Joueur:delete" }
    methods:  DELETE
